name: aspends_tracker
description: A simple yet powerful spend and income tracker app.
version: 5.10.0+9

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.2.3
  pdf: ^3.10.4
  app_links:
  printing: ^5.11.1
  hive_flutter: ^1.1.0
  material_color_utilities: ^0.11.1
  dynamic_color:
  zoom_tap_animation:
  loading_animation_widget:
  flex_color_scheme:
  fl_chart: ^1.0.0
  local_auth: ^2.3.0
  home_widget: ^0.8.0
  excel: ^4.0.6
  stylish_bottom_bar: ^1.1.1
  path_provider: ^2.1.2
  google_fonts: ^6.2.0
  flutter_launcher_icons: ^0.14.4
  csv: ^6.0.0
  file_picker:
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  liquid_glass_renderer:
  image_picker: ^1.1.2
  flutter_displaymode: ^0.6.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_colorpicker: ^1.1.0
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  change_app_package_name: ^1.5.0
enable-impeller: true
flutter:
  uses-material-design: true


  fonts:
    - family: NFont
      fonts:
        - asset: assets/font/RobotoSerif_36pt-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/font/RobotoSerif_36pt-Regular.ttf

flutter_launcher_icons:
  android:
    generate: true
  ios: false
  image_path: "assets/icons/ex.png"


file_picker:
  android:
    enable: true
  ios:
    enable: false
  windows:
    enable: false
  linux:
    enable: false
